### ISSUE TITLE
Distribute the component as a bower package

### ISSUE THREAD

**Issue by nadouani** [ghiscoding/angular-markdown-editor#1]
Hello,

it would be great if this component could be used as a Bower dependency.
I found another project that already reserved your component's name but it's really basic. (https://github.com/JimLiu/angular-markdown-editor)

Thanks

**Comment by ghiscoding** [comment]
Hi,

I already published it on [NPM](https://www.npmjs.com/package/angular-markdown-editor) though, isn't that enough? I could publish on bower but it's just extra steps and I thought NPM is mostly used nowadays.

**Comment by nadouani** [comment]
I think that Bower is also an additional option. For example, the most know angular app generators (the official yeoman one for exemple) uses bower to manage the UI related dependencies (NPM is used for gulp or grunt stuff).

**Comment by ghiscoding** [comment]
Created the `bower.json`, you can run `bower info angular-markdown-editor-ghiscoding` to get the info. I already copied over the dependencies of `NPM` so hopefully they use the same package names or else please make a PR and fix it yourself.

Thanks

**Comment by nadouani** [comment]
Thanks, I'll check the dependencies and let you know. It would be cool if you could register it on bower.io

**Comment by nadouani** [comment]
Ok, it seems like the "highlight.js" bower dependency is not the one your plugin is using. It points to another bower package that no longer exist.

```
bower highlight.js#^9.5.0                           ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/danielditgens/highlight.js.git", exit code of #128 remote: Repository not found. fatal: repository 'https://github.com/danielditgens/highlight.js.git/' not found
```

That said, the correct bower dependency name for the "highlight.js" we need is "highlight.js.origin" [https://github.com/isagalaev/highlight.js](https://github.com/isagalaev/highlight.js)

If you want a PR, I can do it, but a commit from you will be faster :D 

PS: the other dependencies are OK

Cheers

**Comment by ghiscoding** [comment]
Please make a PR since I don't use Bower on my side. 
Make sure that everything else works :) 

Thanks
