### ISSUE TITLE
Markdown editor not applied to any dynamically added textareas

### ISSUE THREAD

**Issue by Shawson** [ghiscoding/angular-markdown-editor#13]
Hi,

I have an angular app which uses routing- at the point the page loads, my editor is off on another routed page so doesn't exist on the page- when i do click the link for my other page, and the new textarea is loaded into the dom, none of the markdown stuff is applied to it.  Is there a way to re-run the init routines that set all this up?

Many thanks,

Shaw

**Comment by ghiscoding** [comment]
Sorry, I have never used it the way you described, so I can't really say. What kind of setup are you talking about? Can't you just save the configs in a global `.config` or `.value`?

**Comment by Shawson** [comment]
It looks like it was caused by a couple problems for me; 

in angular-markdown-editor.js, in the opening few lines I had to make a couple changes to get this to fireup for me;

`

    return {
        restrict: 'A',
        require:  'ngModel',
        link: function(scope, element, attrs, ngModel) {
          var options = scope.$eval(attrs.markdownEditor);

            // Only initialize the $.markdown plugin once.
            if (! element.hasClass('processed')) {
                element.addClass('processed');

                // Setup the markdown WYSIWYG.
                $(element).markdown({
`

Notice I had to wrap the reference to element in a jquery selector $() or the markdown call would fail.  Further down on line 28 I needed to provide a default for the disabledButtons option or the editor wouldn't come back after going into preview mode;

`

                  disabledButtons: options.disabledButtons || [],

`

Not sure why this is only an issue for me though?

**Comment by ghiscoding** [comment]
If it makes the tool better, I would gladly accept a PR.

**Comment by Shawson** [comment]
Created PR #14 !

**Comment by ghiscoding** [comment]
I'd like to do some cleanup on opened tickets and I'm not sure what to do with your open PR. Part of your changes were implemented in a separate [commit](https://github.com/ghiscoding/angular-markdown-editor/commit/da4613ebd1ef7b5c013f72775135c4ca0f34c4b2) that was pushed after your PR. The following code changed is already in the live version

```diff
- hiddenButtons: options.hiddenButtons || null,
- disabledButtons: options.disabledButtons || null,
+ hiddenButtons: options.hiddenButtons || [],
+ disabledButtons: options.disabledButtons || [],
```

Please provide feedback, thank you

**Comment by ghiscoding** [comment]
I guess it is safe to close the issue since you closed the PR that went with it.
