### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by rhclayto** [ghiscoding/angular-markdown-editor#15]
This is caused by the hiddenButtons & disabledButtons options, which, if not set when using the directive, default to `null`. In this case `null` is passed into bootstrap-markdown, which tries to do 

```javascript
__parseButtonNameParam: function(names) {
  return typeof names == 'string' ?
  names.split(' ') :
  names;

},
disableButtons: function(name) {
  var buttons = this.__parseButtonNameParam(name),
    that = this;

    $.each(buttons, function(i, v) {
      that.__alterButtons(buttons[i], function(el) {
        el.removeAttr('disabled');
       });
    });

    return this;
},
```

which throws the error, since `name` is null, & `$.each` doesn't work on null.

When this happens, for instance when switching from preview to editor modes, it kills the editor.

The following changes in `angular-markdown-editor.js` fix it:

```javascript
hiddenButtons: options.hiddenButtons || {},
disabledButtons: options.disabledButtons || {},
```

Changing showButtons, might be wise too:

```javascript
showButtons: options.showButtons || {},
```

**Comment by ghiscoding** [comment]
Made your changes and pushed version `1.1.2`. I ran the demo and it looks ok, you might want to test a bit more though

**Comment by ghiscoding** [comment]
I made some changes from your original request, after looking at `Bootstrap-Markdown` I realized that the `hiddenButtons` and `disabledButtons` should be array not object and so I updated the code (not sure why you proposed object but I decided to change that). A new version `1.1.3` was pushed to address this, thanks

**Comment by rhclayto** [comment]
Yeah, I noticed it was array shortly after posting. Thanks for updating this!
