### ISSUE TITLE
 how to use dropZoneOptions  with angular-markdown-editor?

### ISSUE THREAD

**Issue by monali-jain** [ghiscoding/angular-markdown-editor#21]
I wan to upload file with drag and drop.

I have seen dropZoneOptions in angular-markdown-editor. but not found any document for use of it.

can you please provide any information or example how to use dropZoneOptions  with angular-markdown-editor?

**Comment by ghiscoding** [comment]
I never used it either, This library was made by replicating a few other libraries and most of the options comes from [Bootstrap Markdown](http://www.codingdrama.com/bootstrap-markdown/), that is probably were you will get your answer

**Comment by ghiscoding** [comment]
Since this is a question related to the external library itself, I will close this issue.

**Comment by fangming-ning-sp** [comment]
@ghiscoding I came across the same issue. It seems like it's a dead feature in bootstrap-markdown. If we don't know how to get it to work, I'm wondering if we should remove this option from your library to avoid confusion.
