### ISSUE TITLE
The editor cannot show correctly. $.fn.markdown is undefined

### ISSUE THREAD

**Issue by csps** [ghiscoding/angular-markdown-editor#28]
Hi, I got a problem when I use markdown-editor.
My html:

```html
<div class="col h-100" [ngClass]="{'px-0':!fullScreen}">
            <angular-markdown-editor
            textareaId="editor1" rows="12"
            name="markdownText" [(ngModel)]="markdownText"
            [options]="editorOptions"
            (onChange)="onChange($event.detail.eventData)">
          </angular-markdown-editor>
 </div>
```
My ts below:
```typescript
markdownText: string;
ngOnInit() {
    this.markdownText = '### Markdown example';
    this.editorOptions = {
      iconlibrary: 'fa',
      onShow: (e) => this.bsEditorInstance = e,
      parser: (val) => this.markdownService.compile(val.trim())
    };
  }
```

The editor cannot show correctly.
![image](https://user-images.githubusercontent.com/56900325/68527566-310e9780-0323-11ea-8b88-65ddc354979a.png)
When I open the console, I see the error below:
It seems $.fn.markdown is undefined in angular-markdown-editor.component.ts
![image](https://user-images.githubusercontent.com/56900325/68527559-1f2cf480-0323-11ea-98a7-6d776754aac9.png)

![image](https://user-images.githubusercontent.com/56900325/68527599-9bbfd300-0323-11ea-95da-06ab485b4182.png)

* **Library Version:**
2.0.2

**Please tell us about your environment:**
* **Operating System:
Windows 10

* **Browser:**
Chrome 72.0.3626.121 (Official Build) (64-bit)

* **Language:**
Angular CLI: 6.2.9
Node: 10.15.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@angular/material                 8.2.3
@ngtools/webpack                  7.3.8
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.29.0

**Comment by ghiscoding** [comment]
`$.fn.markdown` is coming from the external library, possibly Bootstrap Markdown. I don't have time to look into this but I suggest you to look at the full demo code on this [angular-markdown-editor-demo](https://github.com/ghiscoding/angular-markdown-editor-demo) repo. 

Just a quick thought, you might have forgot to add Bootstrap Markdown lib to your `angular.json` file as required [here](https://github.com/ghiscoding/angular-markdown-editor#modify-the-angular-clijson-file) so please read the [Installation](https://github.com/ghiscoding/angular-markdown-editor#installation) readme.

**Comment by ghiscoding** [comment]
I'm closing this issue, I'm almost certain you forgot to edit the `angular.json` file as specified in the first page of the repo. You can see the changes in the `angular-markdown-editor-demo` of the `angular.json` on this [line](https://github.com/ghiscoding/angular-markdown-editor-demo/blob/master/angular.json#L24)

I updated the README for the `angular.json`, you need to read this [section](https://github.com/ghiscoding/angular-markdown-editor#modify-the-angular-clijson-file) and apply changes in your setup.
