### ISSUE TITLE
Cross Site Scripting (XSS) via Markdown

### ISSUE THREAD

**Issue by snoopysecurity** [ghiscoding/angular-markdown-editor#29]
**I'm submitting a bug report**

* **Library Version:**
2.0.2

* **Browser:**
all | Chrome  | Firefox

**Current behavior:**
The editor doesn’t do any sort of sanitization of inserted HTML and markdown and this could result in Cross-site Scripting (XSS). An introduction to XSS can be read here: https://excess-xss.com

**Expected/desired behavior:**
I think the best way to fix this would be to use the following JavaScript package https://www.npmjs.com/package/dompurify. DomPurify is XSS sanitizer and is a good solution to prevent XSS. An example of a markdown editor maintainer discussing usage of this can be seen here: https://github.com/nhn/tui.editor/issues/733.

* **What is the expected behavior?**
Steps to Reproduce:
1. Go to https://ghiscoding.github.io/angular-markdown-editor/#/reactive-editor
2. Insert any of the following payloads:
```
![Uh oh...](https://www.example.com/image.png"onload="alert('XSS'))
![Uh oh...]("onerror="alert('XSS'))
[Click Me](javascript:alert('Uh oh...'))
```
* **What is the motivation / use case for changing the behavior?**
Security feature

**Comment by ghiscoding** [comment]
I use DOMPurify in my other library ([Angular-Slickgrid](https://github.com/ghiscoding/Angular-Slickgrid)) but shouldn't that be the responsibility of the user to add such external library?

What I mean is that if you look at what I wrote in the README [here](https://github.com/ghiscoding/angular-markdown-editor#nice-to-have-dependencies), `ngx-markdown` is a nice to use library to preview the markdown but it's not a dependency, you could use whichever other library to see the preview result. 

If I use the code that is written in the README [here](https://github.com/ghiscoding/angular-markdown-editor#preview-button-need-a-parser) for the "Preview Button", I explicitely say that it depends on which library you use and if you use `ngx-mardown` then the code is this
```ts
import { MarkdownService } from 'ngx-markdown';

export class TestComponent implements OnInit {
  constructor(private markdownService: MarkdownService) {}

  ngOnInit() {
    this.editorOptions = {
      parser: (val) => this.markdownService.compile(val.trim())
    };
  }
}
```

then in your case, you would add DOMPurify yourself 
```ts
this.editorOptions = {  
  parser: (val: string) => {
    const sanitizedText = DOMPurify.sanitize(val.trim());
    this.markdownService.compile(sanitizedText);
  }
};
```
So again I don't think it should be the responsibility of this lib to add DOMPurify with a strict dependency. Security is of course important but I think it should be handled by the user of the lib when adding whichever Markdown external library and setting up the `parser` callback.

**Comment by snoopysecurity** [comment]
You are right, I didn't notice the readme (https://github.com/ghiscoding/angular-markdown-editor#nice-to-have-dependencies) when i initially opened this and contacted you. 

hmmm i am not sure about the DOMPurify usage either. Maybe its just worth mentioning DOMPurify as a nice to have dependency and leave it at that. anyone wanting to know more can reopen this or open a new issue.

**Comment by ghiscoding** [comment]
Maybe give it a try first and see if that works for you

**Comment by snoopysecurity** [comment]
So i tested this out, using DOMPurify on the `parser` callback does indeed remove the malicious HTML when clicking on the Preview blue button but i can't seem to clean the output shown in the green Preview pane 


![editor-preview](https://user-images.githubusercontent.com/12512020/74574748-91dde980-4f7c-11ea-9674-873363db1fec.png)

**Comment by ghiscoding** [comment]
Well that text seems to be coming straight from the form [here](https://github.com/ghiscoding/angular-markdown-editor/blob/master/src/app/template/template.component.ts#L83), just sanitize it there then.

**Comment by snoopysecurity** [comment]
Cool! works
