### ISSUE TITLE
Update to Angular 14 required due to deprecated dependencies (core-js)

### ISSUE THREAD

**Issue by Adam-Pond** [ghiscoding/angular-markdown-editor#33]
What are the chances someone could publish an updated version?

warning angular-markdown-editor > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

**Comment by ghiscoding** [comment]
If you want to help and provide Pull Requests to update necessary stuff, I'd be happy to cut a release afterward. I just don't have the bandwidth to work on this at the moment.

**Comment by ghiscoding** [comment]
looking at the `package.json` and I guess that `core-js` and `vinyl-paths` can simply be moved from `dependencies` to `devDependencies` or simply be removed and that would fix the security issues. It would be nice to get a contribution if you're up to it

**Comment by ghiscoding** [comment]
the change is done, see new [v3.0.0](https://github.com/ghiscoding/angular-markdown-editor/releases/tag/v3.0.0) release
