### ISSUE TITLE
Angular 2+ support

### ISSUE THREAD

**Issue by BartNetJS** [ghiscoding/angular-markdown-editor#4]
Hi, any plans for a NG2 version?

**Comment by ghiscoding** [comment]
Not using NG2 yet and probably won't until next year, so if you want to do any PR then go ahead. This is just not a priority for me but feel free to do any PR.

**Comment by ghiscoding** [comment]
Good News the wait will soon be over...
You heard right, it's coming, very, very soon... early next week to be more precised 🐵🙊🙉🙈

**Comment by ghiscoding** [comment]
This is now released, please see new [version 2.x](https://github.com/ghiscoding/angular-markdown-editor/releases/tag/v2.0.2)
