### ISSUE TITLE
vague dependency requirement

### ISSUE THREAD

**Issue by Andrew-Max** [ghiscoding/angular-markdown-editor#5]
Hey,

In the readme it mentions to include the script `<script type="text/javascript" src="../node_modules/angular-markdown-editor/src/angular-markdown-editor.js"></script>`

which if you take that name exactly resolves to another lib which doesn't seem to be a dependency of this lib. Is that supposed to be `angular-markdown-editor-ghiscoding` or does this library actually depend on the node module `angular-markdown-editor` or am I totally misunderstanding this?

**Comment by ghiscoding** [comment]
It seems that you already found the answer... however I added `ghiscoding` (my username) only to the `Bower` package. Why? Because someone else used the same name for his package but only on `Bower` library, it's a little weird, and I only found out later since I added Bower few days after.

**Comment by rhclayto** [comment]
it would be good to change the values in the readme to reflect this fact.

**Comment by ghiscoding** [comment]
@rhclayto the [README - installation](https://github.com/ghiscoding/angular-markdown-editor#installation) already his this information.
