### ISSUE TITLE
Saveable option is not passed right to bootstrap-markdown

### ISSUE THREAD

**Issue by reppners** [ghiscoding/angular-markdown-editor#6]
The `saveable` option is actually spelled `savable` in bootstrap-markdown. This leads to non-functional `saveable` option in this component.

**Comment by ghiscoding** [comment]
Would you be able to make a PR to fix it?

**Comment by ghiscoding** [comment]
Nevermind, I understood after looking at the code. I made fix, actually I accept both `saveable` and `savable`, so if they ever fix it then the package would still work. 

Give it a try, report back if not working. Thanks
