### ISSUE TITLE
markdownEditorObjects Not available(null) when adding options via controller

### ISSUE THREAD

**Issue by srini247** [ghiscoding/angular-markdown-editor#7]
markdownEditorObjects is null when adding options via controller code example

  $("#target-editor").markdown({ 
  onSave: function(e) {
    alert("Saving '"+e.getContent()+"'...")
  }, 
})

Adding editor options from HTML with no controller code does create the markdownEditorObjects but i would like to do it via controller code as i have few custom buttons added.

**Comment by ghiscoding** [comment]
The [Plunker demo](http://plnkr.co/edit/AFxN7uiwkZlJ9OMZwXey?p=info) has example on how to call it, I suggest you take a look at it.

Here's some of the code of the demo
```javascript
$scope.fullScreenPreview = function() {
      $rootScope.markdownEditorObjects.editor1.showPreview();
      $rootScope.markdownEditorObjects.editor1.setFullscreen(true);
}
```

**Comment by srini247** [comment]
Thank you , i think i'm good now.

**Comment by ghiscoding** [comment]
Ok then I'll close the issue
